"""Reg_id, osm_id and wikidata non-unique now

Revision ID: 02fb7eaa5d64
Revises: ac61fd5a3e8f
Create Date: 2025-08-25 21:37:54.708454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fb7eaa5d64'
down_revision = 'ac61fd5a3e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monument', schema=None) as batch_op:
        batch_op.drop_index('ix_monument_reg_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monument', schema=None) as batch_op:
        batch_op.create_index('ix_monument_reg_id', ['reg_id'], unique=1)

    # ### end Alembic commands ###
