"""Use timestamps for needs_info and needs_photos

Revision ID: 6da0511aa4f5
Revises: e0aacb61dade
Create Date: 2025-08-25 16:53:58.248158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da0511aa4f5'
down_revision = 'e0aacb61dade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monument', schema=None) as batch_op:
        batch_op.alter_column('needs_info',
               existing_type=sa.BOOLEAN(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('needs_photos',
               existing_type=sa.BOOLEAN(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_monument_needs_info'), ['needs_info'], unique=False)
        batch_op.create_index(batch_op.f('ix_monument_needs_photos'), ['needs_photos'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monument_needs_photos'))
        batch_op.drop_index(batch_op.f('ix_monument_needs_info'))
        batch_op.alter_column('needs_photos',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('needs_info',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
