"""Make url non-optional in Photo; make filename optional

Revision ID: ac61fd5a3e8f
Revises: ffabc44b0df2
Create Date: 2025-08-25 20:34:45.328889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac61fd5a3e8f'
down_revision = 'ffabc44b0df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.alter_column('thumb_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('full_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.drop_index('ix_photo_full_url')
        batch_op.drop_column('orig_fname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orig_fname', sa.VARCHAR(length=512), nullable=False))
        batch_op.create_index('ix_photo_full_url', ['full_url'], unique=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('full_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('thumb_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###
