"""empty message

Revision ID: e0aacb61dade
Revises: 
Create Date: 2025-08-24 20:19:11.061323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0aacb61dade'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=240), nullable=False),
    sa.Column('email', sa.String(length=240), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_last_login'), ['last_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('monument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('creator', sa.String(length=500), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('built', sa.DateTime(timezone=True), nullable=False),
    sa.Column('multiple', sa.Boolean(), nullable=False),
    sa.Column('reg_id', sa.String(length=120), nullable=True),
    sa.Column('osm_id', sa.String(length=120), nullable=True),
    sa.Column('wikidata', sa.String(length=120), nullable=True),
    sa.Column('genre', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('locality', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=240), nullable=False),
    sa.Column('zip_code', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.REAL(), nullable=False),
    sa.Column('lon', sa.REAL(), nullable=False),
    sa.Column('width_cm', sa.Integer(), nullable=True),
    sa.Column('length_cm', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('moved_id', sa.Integer(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edit', sa.DateTime(), nullable=False),
    sa.Column('needs_info', sa.Boolean(), nullable=False),
    sa.Column('needs_photos', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['moved_id'], ['monument.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id'),
    sa.UniqueConstraint('wikidata')
    )
    with op.batch_alter_table('monument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monument_built'), ['built'], unique=False)
        batch_op.create_index(batch_op.f('ix_monument_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_monument_creator'), ['creator'], unique=False)
        batch_op.create_index(batch_op.f('ix_monument_last_edit'), ['last_edit'], unique=False)
        batch_op.create_index(batch_op.f('ix_monument_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_monument_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_monument_reg_id'), ['reg_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_monument_user_id'), ['user_id'], unique=False)

    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('thumb_key', sa.String(length=512), nullable=False),
    sa.Column('full_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('orig_fname', sa.String(length=512), nullable=False),
    sa.Column('thumb_url', sa.String(length=512), nullable=True),
    sa.Column('full_url', sa.String(length=512), nullable=True),
    sa.Column('monument_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monument_id'], ['monument.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_user_id'))

    op.drop_table('photo')
    with op.batch_alter_table('monument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monument_user_id'))
        batch_op.drop_index(batch_op.f('ix_monument_reg_id'))
        batch_op.drop_index(batch_op.f('ix_monument_name'))
        batch_op.drop_index(batch_op.f('ix_monument_last_seen'))
        batch_op.drop_index(batch_op.f('ix_monument_last_edit'))
        batch_op.drop_index(batch_op.f('ix_monument_creator'))
        batch_op.drop_index(batch_op.f('ix_monument_created_at'))
        batch_op.drop_index(batch_op.f('ix_monument_built'))

    op.drop_table('monument')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_last_login'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    # ### end Alembic commands ###
