"""Make some photo fields nullable

Revision ID: ffabc44b0df2
Revises: 6da0511aa4f5
Create Date: 2025-08-25 20:05:13.820709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffabc44b0df2'
down_revision = '6da0511aa4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.alter_column('caption',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_photo_full_url'), ['full_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_thumb_url'), ['thumb_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_thumb_url'))
        batch_op.drop_index(batch_op.f('ix_photo_full_url'))
        batch_op.alter_column('caption',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
